version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kiwibuild-notify"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tiv3hxqb7x7b"
s3_prefix = "kiwibuild-notify"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SNSTopicARN=\"arn:aws:sns:ap-southeast-2:311908471898:KiwiBuildNotifications\""
