AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  kiwibuild-notify

  Sample SAM Template for kiwibuild-notify

Globals:
  Function:
    Timeout: 15

Resources:
  KiwiBuildNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kiwibuild-notify/
      Handler: kiwibuild-notify
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
            Name: daily-kiwibuild-check
            Description: Kicks off the check for new kiwibuild properties each day
            Enabled: True

Outputs:
  KiwiBuildNotifyFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt KiwiBuildNotifyFunction.Arn
  KiwiBuildNotifyFunctionIamRole:
    Description: "Implicit IAM Role created for KiwiBuildNotify function"
    Value: !GetAtt KiwiBuildNotifyFunctionRole.Arn
