AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  kiwibuild-notify

  Sample SAM Template for kiwibuild-notify

Globals:
  Function:
    Timeout: 15

Resources:
  KiwiBuildScrapeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kiwibuild-scrape/
      Handler: kiwibuild-scrape
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
            Name: daily-kiwibuild-event
            Description: Kicks off the check for new kiwibuild properties each day
            Enabled: True
      Environment:
        Variables:
          KIWIBUILD_URL: https://kiwibuild.govt.nz/available-homes/
          DYNAMODB_TABLE_NAME: !Ref KiwiBuildPropertyTable
          DYNAMODB_TEST_ENDPOINT: http://dynamodb:8000
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref KiwiBuildPropertyTable

  KiwiBuildNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kiwibuild-notify/
      Handler: kiwibuild-notify
      Runtime: go1.x
      Tracing: Active
      Events:
        NewTableRecordsEvent:
          Type: DynamoDB
          Properties:
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 10
            StartingPosition: LATEST
            Stream: !GetAtt KiwiBuildPropertyTable.StreamArn
      Environment:
        Variables:
          SNS_NOTIFICATION_TOPIC: !Ref KiwiBuildNewPropertyNotificationTopic
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName:
              !Select [
                1,
                !Split ["/", !GetAtt KiwiBuildPropertyTable.StreamArn],
              ]
            StreamName:
              !Select [
                3,
                !Split ["/", !GetAtt KiwiBuildPropertyTable.StreamArn],
              ]
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt KiwiBuildNewPropertyNotificationTopic.TopicName

  KiwiBuildPropertyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Property
      KeySchema:
        - AttributeName: Title
          KeyType: HASH
        - AttributeName: Type
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: Title
          AttributeType: S
        - AttributeName: Type
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  KiwiBuildNewPropertyNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: KiwiBuild Notifications
      Subscription:
        - Protocol: email
          Endpoint: hejeune@gmail.com
        - Protocol: email
          Endpoint: ellagriffinking@gmail.com

Outputs:
  KiwiBuildScrapeFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt KiwiBuildScrapeFunction.Arn
  KiwiBuildScrapeFunctionIamRole:
    Description: "Implicit IAM Role created for KiwiBuildNotify function"
    Value: !GetAtt KiwiBuildScrapeFunctionRole.Arn
