AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  kiwibuild-notify

  Sample SAM Template for kiwibuild-notify

Globals:
  Function:
    Timeout: 15

Resources:
  KiwiBuildScrapeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kiwibuild-scrape/
      Handler: kiwibuild-scrape
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
            Name: daily-kiwibuild-check
            Description: Kicks off the check for new kiwibuild properties each day
            Enabled: True
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: Property
          DYNAMODB_TEST_ENDPOINT: "http://dynamodb:8000"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Property

  KiwiBuildPropertyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Property
      KeySchema:
        - AttributeName: Title
          KeyType: HASH
        - AttributeName: Type
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: Title
          AttributeType: S
        - AttributeName: Type
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

Outputs:
  KiwiBuildScrapeFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt KiwiBuildNotifyFunction.Arn
  KiwiBuildScrapeFunctionIamRole:
    Description: "Implicit IAM Role created for KiwiBuildNotify function"
    Value: !GetAtt KiwiBuildNotifyFunctionRole.Arn
