AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sends notifications via phone and email when new properties are listed on the KiwiBuild website.

Parameters:
  SNSTopicARN: # manually managed to keep contact details off GitHub
    Type: String
    Description: The ARN of the manually manages SNS topic to handle notifications.

Globals:
  Function:
    Timeout: 15

Resources:
  KiwiBuildScrapeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kiwibuild-scrape/
      Handler: kiwibuild-scrape
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
            Name: daily-kiwibuild-event
            Description: Kicks off the check for new kiwibuild properties each day
            Enabled: True
      Environment:
        Variables:
          KIWIBUILD_URL: https://kiwibuild.govt.nz/available-homes/
          DYNAMODB_TABLE_NAME: !Ref KiwiBuildPropertyTable
          DYNAMODB_TEST_ENDPOINT: http://dynamodb:8000
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref KiwiBuildPropertyTable

  KiwiBuildNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kiwibuild-notify/
      Handler: kiwibuild-notify
      Runtime: go1.x
      Tracing: Active
      Events:
        NewTableRecordsEvent:
          Type: DynamoDB
          Properties:
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 10
            StartingPosition: LATEST
            Stream: !GetAtt KiwiBuildPropertyTable.StreamArn
      Environment:
        Variables:
          SNS_NOTIFICATION_TOPIC: !Ref SNSTopicARN
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName:
              !Select [
                1,
                !Split ["/", !GetAtt KiwiBuildPropertyTable.StreamArn],
              ]
            StreamName:
              !Select [
                3,
                !Split ["/", !GetAtt KiwiBuildPropertyTable.StreamArn],
              ]
        - SNSPublishMessagePolicy:
            TopicName: !Select [5, !Split [":", !Ref SNSTopicARN]]

  KiwiBuildPropertyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Property
      KeySchema:
        - AttributeName: Title
          KeyType: HASH
        - AttributeName: Type
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: Title
          AttributeType: S
        - AttributeName: Type
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  KiwiBuildScrapeFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt KiwiBuildScrapeFunction.Arn
  KiwiBuildScrapeFunctionIamRole:
    Description: "Implicit IAM Role created for KiwiBuildNotify function"
    Value: !GetAtt KiwiBuildScrapeFunctionRole.Arn
